engines:
  duplication:
    enabled: true
    exclude_paths:
      - Tests/**
exclude_paths:
  - '.bin/**'
  - 'CodeAnalysis/**'
  - 'translations/**'
  - 'views/**'
  - 'WirecardOxidRuleset/**'
  - 'Dockerfile'
