sudo: false
dist: xenial
language: php

services:
  - docker

env:
  global:
    - MYSQL_USER=root
    - MYSQL_PASSWORD=root
    - MYSQL_DATABASE=oxid_db
    - OXID_CONTAINER=oxid_ee_web
    - OXID_VERSION=dev-b-6.1-ce
    - MODULE_NAME=${TRAVIS_REPO_SLUG}
    - MODULE_PATH=wirecard/paymentgateway
    - github_token:
      secure: "Iy/Plz3V++TKSQbz/A0x7ZhETSfcvbXxT4zKQh51W8fjBUlKKrQmDA1rICIjnfFs0bNAe6M2yQxxHgJKUJPBsi9Nk/Ynuk/I5lLK1jLL6THioGB6oKUyRBytlcVLZ+0lNqmV/jRKYdwEPI+jNduCk5GSjubSGMIWGNDcqAUiTu+oy3Gu9FS/auEGxim7UaZYC+MM+7ir0zD6w/0nuCaxalAeLahFz0g3QlXc7FB88SxH//lxzKDZh3U6XKyIEXGG8IQiCYaJRUqr9unzHDVbjOvNT6HWZQ4jGSfnCZTnp4aPfOrk1Ir334/4Cuy4xCP4iiuiRFHoxw++uknh77slUwRtZbrUlwoCbvT0V/GOQaN2HSjrTOc5n1/M0XsPRumbZ+I/4EoCnZUwNiBpWtVhrzSpE84+0BBj67gmStzca1sZMkts+oHnr5S6qajVY5ePY4Sn3rI/JbUJP501zexRHgqKY26a+Hqz9TAnNJqRKfm6ez5pSlXUKk4eCl7slgYuY8I="

matrix:
  include:
    - php: 7.1
    - php: 7.2

    - stage: phraseapp-pull
      if: env(PHRASEAPP_PULL) = '1'
      language: ruby
      ruby: 2.5.3
      before_install: skip
      install:
        - gem install bundler -v 2.0.1
        - travis_retry bundle install
      script:
        - .bin/rake phraseapp:ci_update
      after_script: skip

    - stage: phraseapp-check-if-in-sync
      if: branch = master OR type = pull_request
      language: ruby
      ruby: 2.5.3
      before_install: skip
      install:
        - gem install bundler -v 2.0.1
        - travis_retry bundle install
      script:
        - .bin/rake phraseapp:ci_check_if_in_sync
      after_script: skip

install:
  # build & start containers
  - docker-compose -f docker-compose.ci.yml up --build -d
  # wait till webserver ready
  - timeout 300 bash -c 'while [[ "$(docker exec ${OXID_CONTAINER} curl -Ifs -o /dev/null -w ''%{http_code}'' http://localhost)" != "200" ]]; do sleep 2; done' || false

script:
  - docker exec ${OXID_CONTAINER} phpcs.sh
  - docker exec ${OXID_CONTAINER} phpmd.sh
  - docker exec ${OXID_CONTAINER} runtests-unit-coverage.sh
  - docker exec ${OXID_CONTAINER} bash -c 'reset-shop.sh && runtests-selenium.sh'

after_script:
  - .bin/generate-tag.sh

before_deploy:
  - export REPO_NAME=$(echo ${TRAVIS_REPO_SLUG} | awk -F'/' '{print $2}')
  - export RELEASE_NOTES=$(composer make-release-notes)
  - bash .bin/generate-readme-badge.sh

deploy:
  on:
    repo: ${TRAVIS_REPO_SLUG}
    tags: true
  provider: releases
  # api_key:
  # secure:
  name: '${REPO_NAME} ${TRAVIS_TAG}'
  body: '${RELEASE_NOTES}'
  skip_cleanup: true
